// Generated by Wrangler via `npm run cf-typegen`

interface Env {
  OAUTH_KV: KVNamespace;
  YNAB_OAUTH_CLIENT_ID: string;
  YNAB_OAUTH_CLIENT_SECRET: string;
  YNAB_OAUTH_SCOPE?: string;
  MCP_OBJECT: DurableObjectNamespace<import("./src/index").YnabMCP>;
}
